### ISSUE TITLE
Vectorization of n-gram code to speed up the execution

### ISSUE THREAD

**Issue by NandiniRangaswamy6** [alokrk/csc510groupk#15]
Currently using loops to determine n-grams.

**Comment by karthiksheshadri** [comment]
some clues here: http://stackoverflow.com/questions/22367681/extract-cumulative-n-grams-matlab

will try to modify this afetrnoon

**Comment by karthiksheshadri** [comment]
I don't believe this is possible but I'l try.

**Comment by alokrk** [comment]
Was completed on separate repo. Need to merge.
