### ISSUE TITLE
what should be the output if user inputted keywords are not there in the post

### ISSUE THREAD

**Issue by NandiniRangaswamy6** [alokrk/csc510groupk#21]
currently it prints top 3 posts

**Comment by karthiksheshadri** [comment]
the algorithm is not a keyword search..it's an n gram based similarity score.  A simple way to detect if the post does not address a particular keyword is to see if the edit distance is larger thAN the size of the input keyword. If this is true for a post, assign it's similarity to inf and continue. If all posts have a score of inf, then return  nothing
