### ISSUE TITLE
Finalize the 3 different methods 

### ISSUE THREAD

**Issue by NandiniRangaswamy6** [alokrk/csc510groupk#7]
Discuss and code 3 different ways

**Comment by alokrk** [comment]
Current overview - Explicit feedback, implicit feedback, blind extraction.

**Comment by alokrk** [comment]
Implicit feedback my not be possible. Expand on explicit.

**Comment by rpsingh2** [comment]
Discussed. Matlab  implementations.
1) Naive Bayes
2) Random Forest
3) N-gram
