### ISSUE TITLE
Dataset preprocessing

### ISSUE THREAD

**Issue by alokrk** [alokrk/csc510groupk#9]
Extract data from StackOverflow.

**Comment by alokrk** [comment]
Data upto Jan 1, 2016 has been downloaded from archives.

Need to parse data.

**Comment by NandiniRangaswamy6** [comment]
Wrote a smaple parser.py which takes input as json formatted data file and stores it in dictionaries.

**Comment by alokrk** [comment]
Tags have been extracted in R.
Need to similarly extract other data.

**Comment by alokrk** [comment]
Meta data extraction complete. Implement solution for Delivery.

**Comment by alokrk** [comment]
Completed pulling data into frames.
Scope changed to programmers.stackexchange
